create table estado
(
    codigo serial primary key,
    nome varchar(50) not null
);

INSERT INTO estado (codigo, nome) VALUES
                                       (1, 'Acre'),
                                       (2, 'Alagoas'),
                                       (3, 'Amapá'),
                                       (4, 'Amazonas'),
                                       (5, 'Bahia'),
                                       (6, 'Ceará'),
                                       (7, 'Distrito Federal'),
                                       (8, 'Espírito Santo'),
                                       (9, 'Goiás'),
                                       (10, 'Maranhão'),
                                       (11, 'Mato Grosso'),
                                       (12, 'Mato Grosso do Sul'),
                                       (13, 'Minas Gerais'),
                                       (14, 'Pará'),
                                       (15, 'Paraíba'),
                                       (16, 'Paraná'),
                                       (17, 'Pernambuco'),
                                       (18, 'Piauí'),
                                       (19, 'Rio de Janeiro'),
                                       (20, 'Rio Grande do Norte'),
                                       (21, 'Rio Grande do Sul'),
                                       (22, 'Rondônia'),
                                       (23, 'Roraima'),
                                       (24, 'Santa Catarina'),
                                       (25, 'São Paulo'),
                                       (26, 'Sergipe'),
                                       (27, 'Tocantins');

create table cidade
(
    codigo serial primary key,
    nome varchar(50),
    codigo_estado integer not null,
    foreign key (codigo_estado) references estado(codigo)
);

INSERT INTO cidade (codigo, nome, codigo_estado) VALUES
                                                  (1, 'Araújos', 13),
                                                  (2, 'Arcos', 13),
                                                  (3, 'Bambuí', 13),
                                                  (4, 'Bom Despacho', 13),
                                                  (5, 'Camacho', 13),
                                                  (6, 'Campo Belo', 13),
                                                  (7, 'Candeias', 13),
                                                  (8, 'Carmo da Mata', 13),
                                                  (9, 'Carmo do Cajuru', 13),
                                                  (10, 'Carmópolis de Minas', 13),
                                                  (11, 'Cláudio', 13),
                                                  (12, 'Conceição do Pará', 13),
                                                  (13, 'Divinópolis', 13),
                                                  (14, 'Formiga', 13),
                                                  (15, 'Igaratinga', 13),
                                                  (16, 'Itaúna', 13),
                                                  (17, 'Itapecerica', 13),
                                                  (18, 'Itaguara', 13),
                                                  (19, 'Japaraíba', 13),
                                                  (20, 'Lagoa da Prata', 13),
                                                  (21, 'Leandro Ferreira', 13),
                                                  (22, 'Luz', 13),
                                                  (23, 'Martinho Campos', 13),
                                                  (24, 'Medeiros', 13),
                                                  (25, 'Moema', 13),
                                                  (26, 'Nova Serrana', 13),
                                                  (27, 'Oliveira', 13),
                                                  (28, 'Onça de Pitangui', 13),
                                                  (29, 'Pains', 13),
                                                  (30, 'Pitangui', 13),
                                                  (31, 'Santo Antônio do Monte', 13),
                                                  (32, 'São Francisco de Paula', 13),
                                                  (33, 'São Gonçalo do Pará', 13),
                                                  (34, 'São Roque de Minas', 13),
                                                  (35, 'São Sebastião do Oeste', 13),
                                                  (36, 'Serra da Saudade', 13),
                                                  (37, 'Tapiraí', 13),
                                                  (38, 'Vargem Bonita', 13),
                                                  (39, 'Belo Horizonte', 13),

-- 40 a 72. Municípios da Região Metropolitana de Belo Horizonte (RMBH)
                                                  (40, 'Baldim', 13),
                                                  (41, 'Betim', 13),
                                                  (42, 'Brumadinho', 13),
                                                  (43, 'Caeté', 13),
                                                  (44, 'Capim Branco', 13),
                                                  (45, 'Confins', 13),
                                                  (46, 'Contagem', 13),
                                                  (47, 'Esmeraldas', 13),
                                                  (48, 'Florestal', 13),
                                                  (49, 'Ibirité', 13),
                                                  (50, 'Igarapé', 13),
                                                  (51, 'Itaguara', 13),
                                                  (52, 'Itatiaiuçu', 13),
                                                  (53, 'Jaboticatubas', 13),
                                                  (54, 'Juatuba', 13),
                                                  (55, 'Lagoa Santa', 13),
                                                  (56, 'Mário Campos', 13),
                                                  (57, 'Mateus Leme', 13),
                                                  (58, 'Matozinhos', 13),
                                                  (59, 'Nova Lima', 13),
                                                  (60, 'Nova União', 13),
                                                  (61, 'Pedro Leopoldo', 13),
                                                  (62, 'Raposos', 13),
                                                  (63, 'Ribeirão das Neves', 13),
                                                  (64, 'Rio Acima', 13),
                                                  (65, 'Rio Manso', 13),
                                                  (66, 'Sabará', 13),
                                                  (67, 'Santa Luzia', 13),
                                                  (68, 'São Joaquim de Bicas', 13),
                                                  (69, 'São José da Lapa', 13),
                                                  (70, 'Sarzedo', 13),
                                                  (71, 'Taquaraçu de Minas', 13),
                                                  (72, 'Vespasiano', 13),

-- 73 a 92. Principais cidades do Sul de Minas Gerais
                                                  (73, 'Varginha', 13),
                                                  (74, 'Pouso Alegre', 13),
                                                  (75, 'Poços de Caldas', 13),
                                                  (76, 'Itajubá', 13),
                                                  (77, 'São Lourenço', 13),
                                                  (78, 'Passos', 13),
                                                  (79, 'Alfenas', 13),
                                                  (80, 'Três Corações', 13),
                                                  (81, 'Santa Rita do Sapucaí', 13),
                                                  (82, 'Extrema', 13),
                                                  (83, 'Monte Sião', 13),
                                                  (84, 'Caxambu', 13),
                                                  (85, 'São Thomé das Letras', 13),
                                                  (86, 'Guaxupé', 13),
                                                  (87, 'Paraisópolis', 13),
                                                  (88, 'Ouro Fino', 13),
                                                  (89, 'Lavras', 13),
                                                  (90, 'São Sebastião do Paraíso', 13),
                                                  (91, 'São Gonçalo do Sapucaí', 13),
                                                  (92, 'Três Pontas', 13),
                                                  (93, 'Piumhi', 13);

alter table pessoa drop column cidade;
alter table pessoa drop column estado;
alter table pessoa add column codigo_cidade integer;
alter table pessoa add foreign key (codigo_cidade) references cidade(codigo);

update pessoa set codigo_cidade = 93;
